name: Deploy Content to eco-connector-test [80c4c512-0e0f-404c-b6f3-ae3a8389a34c]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-80c4c512-0e0f-404c-b6f3-ae3a8389a34c.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on: 
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-80c4c512-0e0f-404c-b6f3-ae3a8389a34c.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'eco-connector-test'
      workspaceName: 'eco-connector-test'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_80c4c5120e0f404cb6f3ae3a8389a34c }}
      contentTypes: 'Workbook'

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_80c4c5120e0f404cb6f3ae3a8389a34c }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      run: Start-Sleep -s 30
      shell: powershell
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}

    
    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_80c4c5120e0f404cb6f3ae3a8389a34c }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      run: Start-Sleep -s 30
      shell: powershell
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure' }}
    
    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure'  }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_80c4c5120e0f404cb6f3ae3a8389a34c }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy Content to Azure Sentinel
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}/.github/workflows/azure-sentinel-deploy.ps1
